game_genres = sorted(set([
    "Platformer", "RPG", "Puzzle", "Shooter", "Strategy", "Adventure", "Action",
    "Simulation", "Sports", "Fighting", "Stealth", "Survival", "Horror", "Rhythm",
    "Sandbox", "Open World", "MMORPG", "MOBA", "Battle Royale", "Visual Novel",
    "Idle", "Card Game", "Board Game", "Trivia", "Educational", "Party", "Racing",
    "Music", "Arcade", "Metroidvania", "Roguelike", "Tower Defense", "Turn-Based Strategy",
    "Real-Time Strategy", "Tactical RPG", "Action RPG", "First-Person Shooter",
    "Third-Person Shooter", "Text Adventure", "Interactive Fiction", "Point-and-Click",
    "Hidden Object", "Match-3", "Endless Runner", "Bullet Hell", "Beat 'em up",
    "Hack and Slash", "Tycoon", "City Builder", "Life Simulation", "Dating Sim",
    "Farming Sim", "Flight Sim", "Space Sim", "Vehicle Sim", "Pinball", "Breakout",
    "Maze", "Escape Room", "Deck Builder", "Rhythm Game", "Augmented Reality",
    "Virtual Reality", "Text-Based RPG", "Interactive Movie", "Alternate Reality Game",
    "Art Game", "Experimental", "Game Jam", "Incremental", "Idle Clicker",
    "Physics-Based", "Procedural Generation", "Social Deduction", "Trivia Quiz",
    "Typing Game", "Voice-Controlled", "Walking Simulator", "Wargame", "Word Search",
    "Zombies", "Survival Horror", "Soulslike", "Battle Arena", "Hero Shooter",
    "Auto Battler", "Deckbuilding Roguelike", "Narrative Adventure", "Puzzle Platformer",
    "Stealth Action", "Survival Crafting", "Tower Offense", "Turn-Based Tactics",
    "Real-Time Tactics", "Grand Strategy", "4X Strategy", "City Management",
    "Colony Sim", "God Game", "Medical Sim", "Political Sim", "Space 4X",
    "Sports Management", "Time Management", "Train Sim", "Vehicular Combat",
    "Visual Novel RPG", "Word Puzzle", "Alien Invasion", "Alchemy", "Alternate History",
    "Ancient Civilizations", "Animal Care", "Ant War", "Apocalyptic Survival",
    "Archaeology", "Archery", "Arena Shooter", "Asteroid Defense", "Astrology",
    "Astronomy", "Atompunk", "Aviation", "Bar Management", "Baseball Sim",
    "Basketball Sim", "Beach Games", "Bee Farming", "Billiards", "Bounty Hunter",
    "Business Sim", "Butterfly Collecting", "Candle Making", "Carnival Games",
    "Castle Defense", "Cat Simulator", "Cheese Making", "Chess Sim",
    "City Destruction", "Cloudpunk", "Coffee Shop Sim", "Color Matching",
    "Combat Racing", "Comic Creation", "Commodore Retro", "Conspiracy Theory",
    "Cooking Competition", "Courtroom Drama", "Crime Syndicate", "Cryptography",
    "Cybercrime", "Dance Off", "Data Hacking", "Deep Sea Exploration",
    "Desert Survival", "Detective Mystery", "Digital Art Creation", "Dinosaur Park",
    "Disco Management", "DIY Crafting", "Dragon Taming", "Dream Simulation",
    "Drift Racing", "Drone Racing", "Dungeon Builder", "Dungeon Management",
    "Dynamic Narrative", "Elemental Magic", "Elf Life Sim", "Emotion Control",
    "Espionage", "Ethereal Worlds", "Fairy Tale", "Falconry", "Fantasy Management",
    "Fashion Design", "Fishing Adventure", "Forensics", "Forest Survival",
    "Galactic Strategy", "Gardening", "Geology Adventure", "Ghost Hunting",
    "Gladiator Arenas", "Glitch Art", "Golf Sim", "Gothic Horror",
    "Graffiti Art", "Gravity Manipulation", "Green Energy", "Haunted House",
    "Helicopter Sim", "Hero Management", "Historical War", "Hive Mind",
    "Horse Racing", "Ice Fishing", "Ice Sculpting", "Industrial Revolution",
    "Insect Sim", "Island Survival", "Jet Ski Racing", "Jungle Explorer",
    "Kaiju Battles", "Kingdom Management", "Kite Flying", "Lava Surfing",
    "Law Enforcement Sim", "Lighthouse Keeper", "Lumberjack Sim", "Mad Scientist",
    "Magical Boarding School", "Magical Pet Breeding", "Maritime Trade",
    "Martial Arts Sim", "Maze Runner", "Mech Combat", "Medieval Tournament",
    "Memory Games", "Meteorology Sim", "Mind Control", "Mind Games",
    "Monster Breeding", "Monster Hunting", "Motorcycle Racing", "Mountain Climbing",
    "Murder Mystery", "Museum Management", "Mythological Creatures",
    "Nanotechnology", "Nature Conservation", "Neon Racing", "Nightmare Escape",
    "Ninja Training", "Ocean Exploration", "Oil Tycoon", "Opera House Management",
    "Origami Art", "Outer Space Colonization", "Painting Competition", "Parkour",
    "Pet Care", "Philosophy Adventure", "Photography Sim", "Piano Playing",
    "Pirate Adventure", "Plague Management", "Plant Growth Sim", "Planetary Exploration",
    "Poetry Creation", "Polar Exploration", "Prison Escape", "Quantum Physics Adventure",
    "Quarantine Management", "Railway Empire", "Rare Animal Safari",
    "Rebellion Strategy", "Recycling Sim", "Reptile Care", "Restaurant Management",
    "Riddle Solving", "River Rafting", "Robot Factory", "Robot Wars",
    "Rocket Design", "Rocket Racing", "Rope Climbing", "Royal Intrigue",
    "Sailing Adventure", "Sculpting", "Sea Monster Hunting", "Shadow Puppetry",
    "Shapeshifter Adventure", "Shipwreck Survivor", "Skiing Sim", "Skydiving",
    "Slime Breeding", "Snowboarding", "Society Building", "Space Mining",
    "Space Pirate", "Space Racing", "Space Salvage", "Space-Time Manipulation",
    "Speed Chess", "Spy Thriller", "Stage Performance", "Starship Combat",
    "Stargazing", "Stock Market Sim", "Storm Chasing", "Submarine Adventure",
    "Super Villain Sim", "Sustainability Sim", "Swordsmithing", "Symphony Conductor",
    "Tactical Heist", "Tattoo Design", "Tea Brewing", "Time Management Cooking",
    "Time Manipulation", "Tinker Sim", "Treasure Diving", "Trick Shots",
    "Underground Racing", "Urban Planning", "Vampire Survival", "Vehicle Stunts",
    "Volcano Research", "VR Painting", "Water Polo Sim", "Wedding Planning",
    "Whale Watching", "Wildlife Rescue", "Wilderness Survival", "Wine Tasting",
    "Wizarding School", "Worldbuilding", "Yacht Racing", "Yoga Retreat Sim",
    "Zombie Apocalypse"
]))